project:
  type: website
  output-dir: docs

website:
  title: "unpublishable"
  site-url: https://richardjtelford.github.io/unpublishable/
  description: "Unpublishable thoughts from a palaeoecologist"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/richardjtelford
      - icon: twitter
        href: https://twitter.com/richardjtelford
      - icon: cloud-slash
        href: https://bsky.app/profile/richardjtelford.bsky.social
      - icon: rss
        href: index.xml


format:
  html:
    code-tools: 
      source: true
      toggle: false
      caption: none
    highlight-style: a11y
    theme: 
      light: [flatly]
      dark: [darkly]
    code-link: true

execute: 
  freeze: auto

editor: visual

